env:
  global:
  - SWIFT_BRANCH=swift-4.2.1-release
  - SWIFT_VERSION=swift-4.2.1-RELEASE
matrix:
  include:
  - os: linux
    language: generic
    dist: xenial
    sudo: required
    install:
    - sudo apt-get install clang libicu-dev
    - mkdir swift
    - curl https://swift.org/builds/$SWIFT_BRANCH/ubuntu1404/$SWIFT_VERSION/$SWIFT_VERSION-ubuntu16.04.tar.gz
      -s | tar xz -C swift &> /dev/null
    - export PATH="$(pwd)/swift/$SWIFT_VERSION-ubuntu16.04/usr/bin:$PATH"
    - swift package update
    script:
    - swift test
  - os: osx
    osx_image: xcode10
    language: swift
    script:
    - swift test
notifications:
  email: false
  slack:
    rooms:
      secure: W5g00Y/pYaz8Wb5FIsxNKqf1Jc4iDfUW0ntA0kjiz9c+qsAz4CwvQrRiGX0NZzfp9KirbKHZUsngPDoHH6mYTnzoTwcencvA/+BkH/ckiW+vYcy51poXrrngrVGjDJ3cF9eTv7t0oYFLgj2RIX7Vryh0nwjJteZyItv3ho4ZNTd3wW7eiqDMlfGt21IJSYY6Cdkg2b517WS55cF8G+ATt75Dr79pwWTw8DujtYUxnpuRdnYmT4fO0Wlv8xUThy8G4rnZPz2cQghY88PbBfs/DBsXJTtU/ZWepSNiaOMnNeKk6Ed0MkdEAM5MYFixGQ+RV2dqW7o1caKFUnAQkB2PiXKDXyWkxyCaEOLC1uIGYL/JKpUcP5qzDngvZVWr6jCDmSi8uLyaSpRviZjxS3rYwx69z4Y9/U0xUhEdvd9Zr8PpAgEUcLPMC29U32HGLf1O/pfq4DxqFqWg+GdD5kUStmr4JW5QPCG5Zc7ShL9RTw5BQiLrzbrlY240pdNLgzBPoqbThu7yuGH600Jv95X0fY8r+4jou+EsDqvT4sDRNJGC0oZ8ua52bc90XVxyNjLYJ3b0pCBGcWm6tDtSL4IQR5MvSCd7zSq7gKC9EipMsP8UzXM2k/lOozc4eeuuSg/lQaGUWMmmXsmkh0nzehnwPx30GrHMSo6E95igzSzbGwk=
