#if !canImport(ObjectiveC)
import XCTest

extension JSONDumpTests {
    // DO NOT MODIFY: This is autogenerated, use: 
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__JSONDumpTests = [
        ("testBool", testBool),
        ("testDate", testDate),
        ("testDictionary", testDictionary),
        ("testDouble", testDouble),
        ("testInteger", testInteger),
        ("testNSNumber", testNSNumber),
        ("testNSNumberDouble", testNSNumberDouble),
        ("testNSString", testNSString),
        ("testString", testString),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(JSONDumpTests.__allTests__JSONDumpTests),
    ]
}
#endif
